### ISSUE TITLE
The textColor option doesn't seem to work

### ISSUE THREAD

**Issue by nesk** [etabard/Cordova-PDFReader-IOS#15]
The following options work well but the `textColor` property does nothing:

```js
{
    showShadows: false,
    enableThumbs: false,
    enablePreview: false,
    bookmarks: false,
    landscapeDoublePage: false,
    toolbarBackgroundColor: '#be1717',
    textColor: '#ffffff'
}
```

Also, I'm not sure what the `enablePreview` option does?

**Comment by wim82** [comment]
wondering about this too..

**Comment by etabard** [comment]
It changes the toolbar text color for the "done" button. if enablePreview is true, it show a low quality rendering of the pages before showing the high quality to smooth the look'n feel.
