### ISSUE TITLE
Problem with Hyperlinks in multipage PDF files

### ISSUE THREAD

**Issue by fenta23** [etabard/Cordova-PDFReader-IOS#20]
Hello,
went trough several testings and figured out that there is a problem with multipage PDF + hyperlinks in it.
You can test it with this file: https://github.com/vfr/Reader/blob/master/Resources/Reader.pdf
On the first pages the links are working, on the last one, it's not. :-(

I tried it with the vfr reader: https://github.com/vfr/Reader itself, and there it's fine.

i try to figure out what's going on here, did some tests with easy pdf files, but it seems no problem with the pdf itself.

And of course, the plugin is amazing, i like it very much.

Hope you have an idea.
Regards, Micha

**Comment by etabard** [comment]
Hi, thanks for using this plugin !

The plugin's Reader is no longer updated from "vfr/Reader". I introduced a new feature (landscape double page) and the owner refused to merge it. I really needed that feature and now it's hard to merge...

I never experienced that problem. Does it happen only on the last page? Landscape or portrait? If landscape, single page or double page ?

**Comment by fenta23** [comment]
Thanks for the fast answer,

yes, it's only working in portrait, landscape it's not working.

didn't tried it before;)

landscape double page, and landscape not first page, not sure, is not working.

**Comment by fenta23** [comment]
By the way, i tried the vfr/Reader and it shows pdf in landscape double page. i think he did some improvements in this topic.

**Comment by etabard** [comment]
Thanks, I'll have a look at it ! I'm not sure I can do it today though...

**Comment by fenta23** [comment]
How is it going? Any chances that you can fix this?
Micha.

**Comment by fenta23** [comment]
Hello Etabard,
how is it going? Can yu say if you can have a look on this? I can help with debugging or testing, if you need. And btw, i'm willig to send you some coffee;-) How much do you drink for this kind of issue?

Greetz, Micha.

**Comment by etabard** [comment]
Hi, sorry about the delay. I'm pretty busy with other projects...

Could you try this branch : https://github.com/etabard/Cordova-PDFReader-IOS/tree/2.0
I updated the PDFReader.

Thanks for your feedback

 - Manu

**Comment by fenta23** [comment]
Hey Manu,
no worries mate. Pdf with hyperlinks is working in portrait and landscape mode like expected. 
I will test it thru the day but it looks good. Great work. Thanks.
