### ISSUE TITLE
Open on specific page

### ISSUE THREAD

**Issue by gingerjordan** [etabard/Cordova-PDFReader-IOS#23]
Is it possible to open a pdf on a specific page?

I have tried to pass the page number in the url.

`PDFReader.open(localUrl + '#page' + page, options, onSuccess, onError);`

But this throws a 'filepath error'

**Comment by ronyrun** [comment]
Do you have a sample of your code ?

**Comment by gingerjordan** [comment]
Thanks for replying.  My code involving the plugin is really only the above.  The options I have set are the basic ones from the readme.

If I use PDFReader.open without passing a page parameter in the url `PDFReader.open(localUrl, options, onSuccess, onError);` - the plugin works as expected.

However when I pass the page parameter with the url `PDFReader.open(localUrl + '#page' + page, options, onSuccess, onError);` - I get a 'filepath error'

I was just wondering if the plugin supports opening on specific pages and if I need to do this in a different way than passing the page as a parameter in the url?

**Comment by ronyrun** [comment]
I red the doc and I didn't find anything concerning the page number...

**Comment by etabard** [comment]
Hi,

Sorry for the late answer, I had a lot of work. I pushed a fix. You have now an option (page: int) to change the start page number.
