### ISSUE TITLE
filepath error with existant cordova.file.dataDirectory files

### ISSUE THREAD

**Issue by ronyrun** [etabard/Cordova-PDFReader-IOS#24]
Hello, 

I have a problem, I use window.resolveLocalFileSystemURL to check if my file is available and it is.
then when calling PDFReader 

```
PDFReader.open(local_pdf, options, function(){
          console.log("success Open PDF");
        }, function(e){console.log("error PDF", e);});
```

I got a filepath error on the `cordova.file.dataDirectory + fileName.pdf` path
Do you have any solution ? I maybe need to use another directory ?

Regards,
Ron

**Comment by gingerjordan** [comment]
Hi,

What is your

**Comment by ronyrun** [comment]
Thank you.
